import * as React from 'react';
import { withAITracking } from '@microsoft/applicationinsights-react-js';
import { appInsights, reactPlugin } from "../../helpers/AppInsights";
import { Box, Divider, Paper, Typography } from '@mui/material';
import settings from '../../appSettings.json';
import Routes from '../../constants/Routes';

class PrivacyPolicyPage extends React.Component<any,any> {

  constructor(props:any)
  {
    super(props);
    this.state={
    };

    appInsights.trackPageView({name:'PrivacyPolicyPage',uri:Routes.privacyPolicy});

  }

    public render() {
        return(
          <Box sx={{my:2,display:'flex', justifyContent:'center'}}>
            <Box sx={{maxWidth:'lg'}}>
                <Paper elevation={1} sx={{p:4}}>
                <Typography variant='h2' sx={{fontSize:'2.5em'}}><b>Privacy Policy</b></Typography>
                <Typography paragraph sx={{py:1}}>Effective date: 2023-08-03</Typography>
                <Divider sx={{mb:4, mt:2}}/>
                  <Typography paragraph>1. <b>Introduction</b></Typography>
                  <Typography paragraph>Welcome to <b> {settings.system.appName}</b>.</Typography>
                  <Typography paragraph><b>{settings.system.appName}</b> (“us”, “we”, or “our”) operates <b>{settings.system.appUrl}</b> (hereinafter referred to as <b>“Service”</b>).</Typography>
                  <Typography paragraph>Our Privacy Policy governs your visit to <b>{settings.system.appUrl}</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</Typography>
                  <Typography paragraph>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</Typography>
                  <Typography paragraph>Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“agreement”</b>).</Typography>
                  <Typography paragraph>2. <b>Definitions</b></Typography>
                  <Typography paragraph><b>SERVICE</b> means the {settings.system.appUrl} website operated by {settings.system.appName}.</Typography>
                  <Typography paragraph><b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</Typography>
                  <Typography paragraph><b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</Typography>
                  <Typography paragraph><b>COOKIES</b> are small files stored on your device (computer or mobile device).</Typography>
                  <Typography paragraph><b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</Typography>
                  <Typography paragraph><b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</Typography> <Typography paragraph><b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.</Typography>
                  <Typography paragraph><b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</Typography>
                  <Typography paragraph>3. <b>Information Collection and Use</b></Typography>
                  <Typography paragraph>We collect several different types of information for various purposes to provide and improve our Service to you.</Typography>
                  <Typography paragraph>4. <b>Types of Data Collected</b></Typography>
                  <Typography paragraph><b>Personal Data</b></Typography>
                  <Typography paragraph>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (<b>“Personal Data”</b>). Personally identifiable information may include, but is not limited to:</Typography>
                  <Typography paragraph>0.1. Email address</Typography>
                  <Typography paragraph>0.2. First name and last name</Typography>
                  <Typography paragraph>0.3. Cookies and Usage Data</Typography>
                  <Typography paragraph>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by contacting us by email: {settings.system.supportEmail}.</Typography>
                  <Typography paragraph><b>Usage Data</b></Typography>
                  <Typography paragraph>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<b>“Usage Data”</b>).</Typography>
                  <Typography paragraph>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</Typography>
                  <Typography paragraph>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</Typography>
                  <Typography paragraph><b>Location Data</b></Typography><Typography paragraph>We may use and store information about your location if you give us permission to do so (<b>“Location Data”</b>). We use this data to provide features of our Service, to improve and customize our Service.</Typography><Typography paragraph>You can enable or disable location services when you use our Service at any time by way of your device settings.</Typography>
                  <Typography paragraph><b>Tracking Cookies Data</b></Typography>
                  <Typography paragraph>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</Typography>
                  <Typography paragraph>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</Typography>
                  <Typography paragraph>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</Typography>
                  <Typography paragraph>Examples of Cookies we use:</Typography>
                  <Typography paragraph>0.1. <b>Session Cookies:</b> We use Session Cookies to operate our Service.</Typography>
                  <Typography paragraph>0.2. <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.</Typography>
                  <Typography paragraph>0.3. <b>Security Cookies:</b> We use Security Cookies for security purposes.</Typography>
                  <Typography paragraph>0.4. <b>Advertising Cookies:</b> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</Typography>
                  <Typography paragraph><b>Other Data</b></Typography>
                  <Typography paragraph>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, office location and other data. We may also collect information about your startup, it's location, number of members, and other data.</Typography>
                  <Typography paragraph><b>Other Sources</b></Typography>
                  <Typography paragraph>We receive information about you and your activities on and off the Services from third-party partners, such as advertising and market research partners who provide us with information about your interest in and engagement with our Services.</Typography>
                  <Typography paragraph>5. <b>Use of Data</b></Typography>
                  <Typography paragraph>{settings.system.appName} uses the collected data for various purposes:</Typography>
                  <Typography paragraph>0.1. to provide and maintain our Service;</Typography>
                  <Typography paragraph>0.2. to notify you about changes to our Service;</Typography>
                  <Typography paragraph>0.3. to allow you to participate in interactive features of our Service when you choose to do so;</Typography>
                  <Typography paragraph>0.4. to provide customer support;</Typography>
                  <Typography paragraph>0.5. to gather analysis or valuable information so that we can improve our Service;</Typography>
                  <Typography paragraph>0.6. to monitor the usage of our Service;</Typography>
                  <Typography paragraph>0.7. to detect, prevent and address technical issues;</Typography>
                  <Typography paragraph>0.8. to fulfil any other purpose for which you provide it;</Typography>
                  <Typography paragraph>0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</Typography>
                  <Typography paragraph>0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</Typography>
                  <Typography paragraph>0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</Typography>
                  <Typography paragraph>0.12. in any other way we may describe when you provide the information;</Typography>
                  <Typography paragraph>0.13. for any other purpose with your consent.</Typography>
                  <Typography paragraph>6. <b>Retention of Data</b></Typography>
                  <Typography paragraph>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</Typography>
                  <Typography paragraph>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</Typography>
                  <Typography paragraph>7. <b>Transfer of Data</b></Typography>
                  <Typography paragraph>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</Typography>
                  <Typography paragraph>If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.</Typography>
                  <Typography paragraph>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</Typography>
                  <Typography paragraph>{settings.system.appName} will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</Typography>
                  <Typography paragraph>8. <b>Disclosure of Data</b></Typography>
                  <Typography paragraph>We may disclose personal information that we collect, or you provide.</Typography>
                  <Typography paragraph>0.1. <b>Disclosure for Law Enforcement.</b></Typography><Typography paragraph>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</Typography><Typography paragraph>0.2. <b>Business Transaction.</b></Typography><Typography paragraph>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</Typography><Typography paragraph>0.3. <b>Other cases. We may disclose your information also:</b></Typography><Typography paragraph>0.3.1. to our subsidiaries and affiliates;</Typography><Typography paragraph>0.3.2. to contractors, service providers, and other third parties we use to support our business;</Typography><Typography paragraph>0.3.3. to fulfill the purpose for which you provide it;</Typography><Typography paragraph>0.3.4. for the purpose of including your company’s logo on our website;</Typography><Typography paragraph>0.3.5. for any other purpose disclosed by us when you provide the information;</Typography><Typography paragraph>0.3.6. with your consent in any other cases;</Typography><Typography paragraph>0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</Typography>
                  <Typography paragraph>9. <b>Security of Data</b></Typography>
                  <Typography paragraph>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</Typography>
                  <Typography paragraph>10. <b>Service Providers</b></Typography>
                  <Typography paragraph>We may employ third party companies and individuals to facilitate our Service (<b>“Service Providers”</b>), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</Typography>
                  <Typography paragraph>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</Typography>
                  <Typography paragraph>11. <b>Analytics</b></Typography>
                  <Typography paragraph>We may use third-party Service Providers to monitor and analyze the use of our Service.</Typography>
                  <Typography paragraph>12. <b>CI/CD tools</b></Typography>
                  <Typography paragraph>We may use third-party Service Providers to automate the development process of our Service.</Typography>
                  <Typography paragraph>13. <b>Advertising</b></Typography><Typography paragraph>We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</Typography>
                  <Typography paragraph>14. <b>Behavioral Remarketing</b></Typography>
                  <Typography paragraph>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</Typography>
                  <Typography paragraph>15. <b>Payments</b></Typography><Typography paragraph>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</Typography><Typography paragraph>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.</Typography>
                  <Typography paragraph>16. <b>Links to Other Sites</b></Typography>
                  <Typography paragraph>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</Typography>
                  <Typography paragraph>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Typography>
                  <Typography paragraph>17. <b>Children’s Privacy</b></Typography>
                  <Typography paragraph>Our Services are not intended for use by children under the age of 18 (<b>“Child”</b> or <b>“Children”</b>).</Typography>
                  <Typography paragraph>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</Typography>
                  <Typography paragraph>18. <b>Changes to This Privacy Policy</b></Typography>
                  <Typography paragraph>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</Typography>
                  <Typography paragraph>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</Typography>
                  <Typography paragraph>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</Typography>
                  <Typography paragraph>19. <b>Contact Us</b></Typography>
                  <Typography paragraph>If you have any questions about this Privacy Policy, please contact us by email: <b>{settings.system.supportEmail}</b>.</Typography>

                </Paper>
            </Box>
            </Box>
        )
    }
}

export default withAITracking(reactPlugin,PrivacyPolicyPage);